name: Deploy Full-Stack Chat App

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Deploy to EC2 via SSH
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.SSH_USER }}       # usually 'ubuntu'
          key: ${{ secrets.EC2_KEY }}            # full .pem content
          port: 22                               # default SSH port
          script_stop: true                       # stop workflow if SSH fails
          script: |
            echo "✅ Connected to EC2"

            # Create folder if it doesn't exist
            cd ~ || mkdir ~/chatapp
            cd ~/chatapp

            # Pull latest code or clone if first deploy
            if [ -d ".git" ]; then
              git pull
            else
              git clone https://github.com/Unicron-2028/Assignment-1-for-internship.git .
            fi

            # Backend setup
            cd backend
            npm install
            pm2 restart backend || pm2 start index.js --name backend

            # Frontend setup
            cd ../frontend
            npm install
            npm run build

            echo "✅ Deployment finished"
