name: Deploy Full-Stack Chat App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: 22
          script: |
            cd ~/ || mkdir ~/chatapp
            cd ~/chatapp
            if [ -d ".git" ]; then git pull; else git clone https://github.com/<Unicron-2028>/Assignment-1-for-internship.git .; fi

            cd backend
            npm install
            pm2 restart backend || pm2 start index.js --name backend

            cd ../frontend
            npm install
            npm run build
